name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Run test
      run: go test -race -coverprofile=tmp_coverage.out -covermode=atomic ./...

    - name: Prepare coverage
      run: cat tmp_coverage.out | grep -v "mock_" > coverage.out

    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)

